name = input("What is your name?: ")
age = int(input("How old are you?: "))
height = float(input("How tall are you?: "))
print("Congratulations!!" + name)
print("You are ageing gracefully")
print("You are "+str(height)+"cm tall")